### ISSUE TITLE
calculate_ani.py/ANIb/fragment_input_files can ignore most of the input sequences

### ISSUE THREAD

**Issue by DWgit** [widdowquinn/scripts#6]
In calculate_ani.py/ANIb/fragment_input_files, there's a small but serious bug. 

The statement `i, count = 0, 0` should be broken up, so that _i_ is set _once per input sequence_. The consequence is that very little of the input FASTA files are written and BLASTed, so the resulting ANI reflects only a tiny sample of the input genomes. 

Fix is easy, attached.

[patch_FIXED_2.txt](https://github.com/widdowquinn/scripts/files/190734/patch_FIXED_2.txt)

**Comment by widdowquinn** [comment]
Thanks DWgit - you are correct. 

This script has since been superseded by [`pyani`](https://github.com/widdowquinn/pyani), which doesn't have this issue, and I would suggest you move over to using that, rather than continue with `calculate_ani.py`.

**Comment by DWgit** [comment]
Thanks very much. I'll shift to pyani.
